"""
ETL — BMW Global Sales Dataset (2010-2024) → knowledge_base.pl
Reads 'archive.zip' (Kaggle download) or 'BMW sales data (2010-2024).csv' directly
and produces Prolog facts in the form:
  bmw(model, year, region, fuel_type, transmission, engine_size_l, price_usd, sales_volume).
"""

import csv
import re
import sys
import zipfile
import os
from io import TextIOWrapper
from typing import Optional

CSV_NAME = "BMW sales data (2010-2024).csv"
ZIP_NAME = "archive.zip"
OUTPUT   = "knowledge_base.pl"

FIELDS = ["Model", "Year", "Region", "Fuel_Type",
          "Transmission", "Engine_Size_L", "Price_USD", "Sales_Volume"]


def to_atom(value: str) -> str:
    """Normalise a string to a valid lowercase Prolog atom.
    Atoms starting with a digit must be single-quoted (e.g. '5_series').
    """
    v = value.strip().lower()
    v = re.sub(r"[^a-z0-9]+", "_", v)   # replace non-alphanum runs with _
    v = v.strip("_")
    v = v or "unknown"
    if v[0].isdigit():
        return f"'{v}'"
    return v


def open_csv():
    """Return a text stream for the CSV, whether it lives in a zip or plain."""
    if os.path.exists(ZIP_NAME):
        z = zipfile.ZipFile(ZIP_NAME)
        return TextIOWrapper(z.open(CSV_NAME), encoding="utf-8-sig")
    if os.path.exists(CSV_NAME):
        return open(CSV_NAME, encoding="utf-8-sig", newline="")
    sys.exit(f"ERROR: neither '{ZIP_NAME}' nor '{CSV_NAME}' found.")


def parse_row(row: dict) -> Optional[str]:
    """Convert one CSV row to a Prolog fact string, or None if invalid."""
    try:
        model        = to_atom(row["Model"])
        year         = int(row["Year"])
        region       = to_atom(row["Region"])
        fuel_type    = to_atom(row["Fuel_Type"])
        transmission = to_atom(row["Transmission"])
        engine_size  = float(row["Engine_Size_L"])
        price_usd    = int(float(row["Price_USD"]))
        sales_volume = int(float(row["Sales_Volume"]))
    except (ValueError, KeyError):
        return None

    return (
        f"bmw({model}, {year}, {region}, {fuel_type}, "
        f"{transmission}, {engine_size}, {price_usd}, {sales_volume})."
    )


def main():
    facts = []
    skipped = 0

    with open_csv() as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            fact = parse_row(row)
            if fact:
                facts.append(fact)
            else:
                skipped += 1

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write("% knowledge_base.pl — BMW Global Sales (2010-2024)\n")
        out.write(f"% {len(facts)} facts generated by etl.py\n\n")
        for fact in facts:
            out.write(fact + "\n")

    print(f"Done: {len(facts)} facts written to '{OUTPUT}' ({skipped} rows skipped).")


if __name__ == "__main__":
    main()
